/**:
  ros__parameters:
   Lidar_front_end/lidar_type: 4   # 1 for Livox-avia, 3 for Ouster-OS1-64, 4 for VLP_32C
   Lidar_front_end/N_SCANS: 6
   Lidar_front_end/using_raw_point: 1
   Lidar_front_end/point_step: 1

   # LiDAR to IMU extrinsic
   Lidar_front_end/lidar2imu_R:
      [0.0, 0.0, 1.0,
       -1.0, 0.0, 0.0,
       0.0, -1.0, 0.0]
   Lidar_front_end/lidar2imu_t: [1.0,0.0,0.0]

   r3live_common/record_offline_map: 1            # If recording offline map. [default = 1]
   r3live_common/pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   r3live_common/minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01]
   r3live_common/image_downsample_ratio: 1.0        # The downsample ratio of the input image. [default = 1]
   r3live_common/estimate_i2c_extrinsic: 1        # If enable estimate the extrinsic between camera and IMU. [default = 1]
   r3live_common/estimate_intrinsic: 1            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1]
   r3live_common/maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   r3live_common/append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]

   # IMPORTANT: /LiDAR_pointcloud_topic should not be modified. LiDAR_front_end will publish the pointcloud to this topic.
   # Gazebo ROS bridge topics
   r3live_common/IMU_topic: "/livox/imu"
   r3live_common/Image_topic: "/camera/image_color"

   # Field experiment topics
   # r3live_common/IMU_topic: "/imu_pole"
   # r3live_common/Image_topic: "/webcam"

   r3live_vio/image_width: 1280
   r3live_vio/image_height: 1024
   r3live_vio/camera_intrinsic:
      [863.4241, 0.0, 640.6808,
      0.0,  863.4171, 518.3392,
      0.0, 0.0, 1.0 ]
   r3live_vio/camera_dist_coeffs: [-0.1080, 0.1050, -1.2872e-04, 5.7923e-05, -0.0222]  #k1, k2, p1, p2, k3

   # [Extrinsic from IMU to Camera] (LiDAR and IMU are superposated by default, but I added a transform in LiDAR_front_end.cpp)
   r3live_vio/camera_ext_R:
         [-0.00113207, -0.0158688, 0.999873,
            -0.9999999,  -0.000486594, -0.00113994,
            0.000504622,  -0.999874,  -0.0158682]
   # camera_ext_t: [0.050166, 0.0474116, -0.0312415]
   r3live_vio/camera_ext_t: [0.0,0.0,0.0]
   # Rough extrinsic value, form CAD model, is not correct enough, but can be online calibrated in our datasets.
   # camera_ext_R:
   #    [0, 0, 1,
   #     -1, 0, 0,
   #     0, -1, 0]
   # camera_ext_t: [0.0,0.0,0.0]

   r3live_lio/lio_update_point_step: 4   # Point step used for LIO update.
   r3live_lio/max_iteration: 2           # Maximum times of LIO esikf.
   r3live_lio/lidar_time_delay: 0.0        # The time-offset between LiDAR and IMU, provided by user.
   r3live_lio/filter_size_corner: 0.30
   r3live_lio/filter_size_surf: 0.30
   r3live_lio/filter_size_surf_z: 0.30
   r3live_lio/filter_size_map: 0.30